//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_BE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Examen_NombreApellidoEntities : DbContext
    {
        public Examen_NombreApellidoEntities()
            : base("name=Examen_NombreApellidoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<LoginUsuario> LoginUsuario { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Sp_Login(Nullable<int> idUsuario, string pass)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Login", idUsuarioParameter, passParameter);
        }
    
        public virtual ObjectResult<usp_Listarusuario_Result> usp_Listarusuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Listarusuario_Result>("usp_Listarusuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<usp_ListarUsuarios_Result> usp_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUsuarios_Result>("usp_ListarUsuarios");
        }
    
        public virtual int Usp_AdministrarUsuario(Nullable<int> idusuario, string nombre, string apellido, string puesto, Nullable<int> estado)
        {
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var puestoParameter = puesto != null ?
                new ObjectParameter("puesto", puesto) :
                new ObjectParameter("puesto", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_AdministrarUsuario", idusuarioParameter, nombreParameter, apellidoParameter, puestoParameter, estadoParameter);
        }
    }
}
