//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExamen.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        int ValidarUsuario(int username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<int> ValidarUsuarioAsync(int username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuario", ReplyAction="http://tempuri.org/IService1/ListarUsuarioResponse")]
        Login_BE.usp_Listarusuario_Result ListarUsuario(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuario", ReplyAction="http://tempuri.org/IService1/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<Login_BE.usp_Listarusuario_Result> ListarUsuarioAsync(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuarios", ReplyAction="http://tempuri.org/IService1/ListarUsuariosResponse")]
        Login_BE.usp_ListarUsuarios_Result[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuarios", ReplyAction="http://tempuri.org/IService1/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<Login_BE.usp_ListarUsuarios_Result[]> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebExamen.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebExamen.ServiceReference1.IService1>, WebExamen.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ValidarUsuario(int username, string pass) {
            return base.Channel.ValidarUsuario(username, pass);
        }
        
        public System.Threading.Tasks.Task<int> ValidarUsuarioAsync(int username, string pass) {
            return base.Channel.ValidarUsuarioAsync(username, pass);
        }
        
        public Login_BE.usp_Listarusuario_Result ListarUsuario(int idusuario) {
            return base.Channel.ListarUsuario(idusuario);
        }
        
        public System.Threading.Tasks.Task<Login_BE.usp_Listarusuario_Result> ListarUsuarioAsync(int idusuario) {
            return base.Channel.ListarUsuarioAsync(idusuario);
        }
        
        public Login_BE.usp_ListarUsuarios_Result[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<Login_BE.usp_ListarUsuarios_Result[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
    }
}
