//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFerreteria.SRVCriptografia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRVCriptografia.ICriptografia")]
    public interface ICriptografia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriptografia/Encriptar", ReplyAction="http://tempuri.org/ICriptografia/EncriptarResponse")]
        string Encriptar(string valor, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriptografia/Encriptar", ReplyAction="http://tempuri.org/ICriptografia/EncriptarResponse")]
        System.Threading.Tasks.Task<string> EncriptarAsync(string valor, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriptografia/Desencriptar", ReplyAction="http://tempuri.org/ICriptografia/DesencriptarResponse")]
        string Desencriptar(string valor, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriptografia/Desencriptar", ReplyAction="http://tempuri.org/ICriptografia/DesencriptarResponse")]
        System.Threading.Tasks.Task<string> DesencriptarAsync(string valor, string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriptografiaChannel : WebFerreteria.SRVCriptografia.ICriptografia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriptografiaClient : System.ServiceModel.ClientBase<WebFerreteria.SRVCriptografia.ICriptografia>, WebFerreteria.SRVCriptografia.ICriptografia {
        
        public CriptografiaClient() {
        }
        
        public CriptografiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriptografiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriptografiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriptografiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Encriptar(string valor, string key) {
            return base.Channel.Encriptar(valor, key);
        }
        
        public System.Threading.Tasks.Task<string> EncriptarAsync(string valor, string key) {
            return base.Channel.EncriptarAsync(valor, key);
        }
        
        public string Desencriptar(string valor, string key) {
            return base.Channel.Desencriptar(valor, key);
        }
        
        public System.Threading.Tasks.Task<string> DesencriptarAsync(string valor, string key) {
            return base.Channel.DesencriptarAsync(valor, key);
        }
    }
}
