
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sunat_BE
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    public string IdEmpresa { get; set; }

    public string Nombre { get; set; }

    public string Llave { get; set; }

    public Nullable<int> Estado { get; set; }

}

}
