
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sunat_BE
{

using System;
    using System.Collections.Generic;
    
public partial class Token
{

    public int IdToken { get; set; }

    public string IdUsuario { get; set; }

    public string Token1 { get; set; }

    public Nullable<System.DateTime> FechaUltimaAccion { get; set; }

    public Nullable<System.DateTime> FechaCaducidad { get; set; }

}

}
