
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sunat_BE
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario1
{

    public string IdUsuario { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Clave { get; set; }

    public Nullable<int> Estado { get; set; }

}

}
